In [1]:
import pandas as pd
import numpy as np
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /home/admin1/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/admin1/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to /home/admin1/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /home/admin1/nltk_data...

True

In [3]:
text = """Iris dataset is widely used in machine learning.
It contains sepal and petal measurements of flowers."""
print(text)

Iris dataset is widely used in machine learning.
It contains sepal and petal measurements of flowers.

In [4]:
tokens = word_tokenize(text)
print("Tokens:\n", tokens)

Tokens:
 ['Iris', 'dataset', 'is', 'widely', 'used', 'in', 'machine', 'learning', '.', 'It', 'contains', 'sepal', 'and', 'petal', 'measurements', 'of', 'flowers', '.']

In [5]:
pos_tags = nltk.pos_tag(tokens)
print("POS Tags:\n", pos_tags)

POS Tags:
 [('Iris', 'NNP'), ('dataset', 'NN'), ('is', 'VBZ'), ('widely', 'RB'), ('used', 'VBN'), ('in', 'IN'), ('machine', 'NN'), ('learning', 'NN'), ('.', '.'), ('It', 'PRP'), ('contains', 'VBZ'), ('sepal', 'JJ'), ('and', 'CC'), ('petal', 'JJ'), ('measurements', 'NNS'), ('of', 'IN'), ('flowers', 'NNS'), ('.', '.')]

In [6]:
stop_words = set(stopwords.words('english'))

filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
print("After Stopword Removal:\n", filtered_tokens)

After Stopword Removal:
 ['Iris', 'dataset', 'widely', 'used', 'machine', 'learning', '.', 'contains', 'sepal', 'petal', 'measurements', 'flowers', '.']

In [7]:
stemmer = PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in filtered_tokens]
print("Stemmed Words:\n", stemmed_words)

Stemmed Words:
 ['iri', 'dataset', 'wide', 'use', 'machin', 'learn', '.', 'contain', 'sepal', 'petal', 'measur', 'flower', '.']

In [8]:
lemmatizer = WordNetLemmatizer()

lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_tokens]
print("Lemmatized Words:\n", lemmatized_words)

Lemmatized Words:
 ['Iris', 'dataset', 'widely', 'used', 'machine', 'learning', '.', 'contains', 'sepal', 'petal', 'measurement', 'flower', '.']

In [9]:
df = pd.read_csv("iris.csv")
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [12]:
df['text'] = df.astype(str).agg(' '.join, axis=1)

df[['text']].head()

                                            text
0  5.1 3.5 1.4 0.2 Setosa 5.1 3.5 1.4 0.2 Setosa
1  4.9 3.0 1.4 0.2 Setosa 4.9 3.0 1.4 0.2 Setosa
2  4.7 3.2 1.3 0.2 Setosa 4.7 3.2 1.3 0.2 Setosa
3  4.6 3.1 1.5 0.2 Setosa 4.6 3.1 1.5 0.2 Setosa
4  5.0 3.6 1.4 0.2 Setosa 5.0 3.6 1.4 0.2 Setosa

In [13]:
documents = df['text'].tolist()

print(documents[:3])

['5.1 3.5 1.4 0.2 Setosa 5.1 3.5 1.4 0.2 Setosa', '4.9 3.0 1.4 0.2 Setosa 4.9 3.0 1.4 0.2 Setosa', '4.7 3.2 1.3 0.2 Setosa 4.7 3.2 1.3 0.2 Setosa']

In [14]:
vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

In [16]:
feature_names = vectorizer.get_feature_names_out()
print(feature_names)

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names_out'

In [17]:
feature_names = vectorizer.get_feature_names()

In [18]:
print(feature_names)

['setosa', 'versicolor', 'virginica']

In [19]:
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

tfidf_df.head()

   setosa  versicolor  virginica
0     1.0         0.0        0.0
1     1.0         0.0        0.0
2     1.0         0.0        0.0
3     1.0         0.0        0.0
4     1.0         0.0        0.0

In [20]:
tfidf_df.iloc[0]

setosa        1.0
versicolor    0.0
virginica     0.0
Name: 0, dtype: float64